[package]
name = "steam-session-proto"
version = "0.1.0"
authors = ["Julia"]
edition = "2018"
description = "Protobuf structs used for Steam sessions"
license = "MIT"

[dependencies]
protobuf = "=3.5.1"

[build-dependencies]
protobuf = "=3.5.1"
protobuf-codegen = "=3.5.1"
